events {
    worker_connections 1024;
}

http {
    real_ip_header X-Forwarded-For;
    set_real_ip_from 0.0.0.0/0;

    geo $ru_ip {
        default 0;
        include /etc/nginx/ip.txt; 
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            if ($ru_ip) {
                return 200 '<h1>РУССКИЙ АЙПИШНИК ОБНАРУЖЕН. ВХОД ВОСПРЕЩЕН</h1>\n';
            }
            proxy_pass http://app_cont:8000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}